# Carregando bibliotecas e arquivos
-------------------------------------------------------------
-------------------------------------------------------------


In [1]:
#Importando bibliotecas
import numpy as np		
import pandas as pd		
import plotly.express as px																				

## Importando os dados e fazendo verificações iniciais
-------------------------------------------------------------

In [2]:
dados = pd.read_excel("/content/drive/MyDrive/MACHINE_LEARNNING/telecom_users.xlsx")		

In [3]:
dados.head()

IDCliente     Genero Dependentes  MesesComoCliente ServicoTelefone  \
0  0002-ORFBO   Feminino         Sim                 9             Sim   
1  0003-MKNFE  Masculino         Nao                 9             Sim   
2  0004-TLHLJ  Masculino         Nao                 4             Sim   
3  0011-IGKFF  Masculino         Nao                13             Sim   
4  0013-EXCHZ   Feminino         Nao                 3             Sim   

   ValorTelefone MultiplasLinhas ServicoInternet  ValorInternet  \
0           54.9             Nao             DSL           94.9   
1           54.9             Sim             DSL           94.9   
2           54.9             Nao           Fibra          129.9   
3           54.9             Nao           Fibra          129.9   
4           54.9             Nao           Fibra          129.9   

  ServicoSegurancaOnline  ...  ServicoSuporteTecnico ServicoStreamingTV  \
0                    Nao  ...                    Sim                Sim   
1                    Nao  ...                    Nao                Nao   
2                    Nao  ...                    Nao                Nao   
3                    Nao  ...                    Nao                Sim   
4                    Nao  ...                    Sim                Sim   

   ValorServiçoStreaming ServicoFilmes ValorServicoFilmes TipoContrato  \
0                   39.9           Nao                0.0        Anual   
1                    0.0           Sim               19.9       Mensal   
2                    0.0           Nao                0.0       Mensal   
3                   39.9           Sim               19.9       Mensal   
4                   39.9           Nao                0.0       Mensal   

   FaturaDigital    FormaPagamento  ValorMensal Churn  
0            Sim    BoletoImpresso        199.6   Nao  
1            Nao    BoletoImpresso        169.7   Nao  
2            Sim  BoletoEletronico        184.8   Sim  
3            Sim  BoletoEletronico        254.5   Sim  
4            Sim    BoletoImpresso        224.7   Sim  

[5 rows x 24 columns]

In [4]:
dados=dados.drop(["IDCliente"],axis=1 )		# Eliminando a coluna IDCliente

# Análise dos dados
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

## Análise das variáveis
--------------------------------------------------------------------------------


In [5]:
dados.dtypes  # Visualizando o tipo de dado por coluna

Genero                     object
Dependentes                object
MesesComoCliente            int64
ServicoTelefone            object
ValorTelefone             float64
MultiplasLinhas            object
ServicoInternet            object
ValorInternet             float64
ServicoSegurancaOnline     object
ValorSegurancaOnline      float64
ServicoBackupOnline        object
ValorBackupOnline         float64
ProtecaoEquipamento        object
ServicoSuporteTecnico      object
ServicoStreamingTV         object
ValorServiçoStreaming     float64
ServicoFilmes              object
ValorServicoFilmes        float64
TipoContrato               object
FaturaDigital              object
FormaPagamento             object
ValorMensal               float64
Churn                      object
dtype: object

In [6]:
dados["Genero"].value_counts()  # Contabilizando clientes masculinos e femininos

Masculino    3050
Feminino     2936
Name: Genero, dtype: int64

In [7]:
# Contabilizando cancelamentos
display(dados["Churn"].value_counts(normalize=True).map("{:.1%}".format))

Nao    73.5%
Sim    26.5%
Name: Churn, dtype: object

In [8]:
#Contabilizando dependentes
display(dados["Dependentes"].value_counts(normalize=True).map("{:.1%}".format))

Nao    70.1%
Sim    29.9%
Name: Dependentes, dtype: object

In [9]:
# Contabilizando formas de pagamento
display(dados["FormaPagamento"].value_counts(normalize=True).map("{:.1%}".format))

BoletoEletronico    33.5%
BoletoImpresso      22.9%
DebitoAutomatico    21.9%
CartaoCredito       21.8%
Name: FormaPagamento, dtype: object

In [10]:
display(dados["FaturaDigital"].value_counts(normalize=True).map("{:.1%}".format))

Sim    58.9%
Nao    41.1%
Name: FaturaDigital, dtype: object

## Verificando e corrigindo valores nulos ( NAN )
-------------------------------------------------------------



In [11]:
# Relação de quantidade
dados.isnull().sum()  # Soma por categoria ( coluna ) todos os valores nulos ( NAN )

Genero                    0
Dependentes               1
MesesComoCliente          0
ServicoTelefone           0
ValorTelefone             0
MultiplasLinhas           0
ServicoInternet           0
ValorInternet             0
ServicoSegurancaOnline    0
ValorSegurancaOnline      0
ServicoBackupOnline       0
ValorBackupOnline         0
ProtecaoEquipamento       0
ServicoSuporteTecnico     0
ServicoStreamingTV        0
ValorServiçoStreaming     0
ServicoFilmes             0
ValorServicoFilmes        0
TipoContrato              0
FaturaDigital             0
FormaPagamento            0
ValorMensal               0
Churn                     1
dtype: int64

In [12]:
# Eliminando dados NAN ( quantidade:2, insignificante para o modelo)
dados2 = dados.dropna() # Criando novo dataframe para mantar a integridade do dataframe original

In [13]:
dados2.isnull().sum() 

Genero                    0
Dependentes               0
MesesComoCliente          0
ServicoTelefone           0
ValorTelefone             0
MultiplasLinhas           0
ServicoInternet           0
ValorInternet             0
ServicoSegurancaOnline    0
ValorSegurancaOnline      0
ServicoBackupOnline       0
ValorBackupOnline         0
ProtecaoEquipamento       0
ServicoSuporteTecnico     0
ServicoStreamingTV        0
ValorServiçoStreaming     0
ServicoFilmes             0
ValorServicoFilmes        0
TipoContrato              0
FaturaDigital             0
FormaPagamento            0
ValorMensal               0
Churn                     0
dtype: int64

## Criando gráficos com as variáveis ( colunas )
-------------------------------------------------------------


In [14]:
# Criando histogramas com Plotly para verificar a relação entre as categorias e o cancelamento ( CHURN )
for coluna in dados2:      
        fig = px.histogram(dados2, x=coluna,nbins=60, color="Churn")
        fig.show()

## Análise estatística descritiva
-------------------------------------------------------------

In [15]:
# resumo estatistico descritivo usando apenas as colunas com dados numéricos
dados2.describe()   

MesesComoCliente  ValorTelefone  ValorInternet  ValorSegurancaOnline  \
count       5984.000000     5984.00000    5984.000000           5984.000000   
mean          32.456551       99.65752     128.135963              2.832353   
std           24.511387       68.38464     104.312756              4.474530   
min            0.000000        0.00000       0.000000              0.000000   
25%            9.000000       54.90000      94.900000              0.000000   
50%           29.000000       74.90000      94.900000              0.000000   
75%           56.000000      149.90000     149.900000              9.900000   
max           72.000000      299.90000     319.900000              9.900000   

       ValorBackupOnline  ValorServiçoStreaming  ValorServicoFilmes  \
count        5984.000000            5984.000000         5984.000000   
mean            3.456066              15.369235            7.775100   
std             4.719575              19.418602            9.710204   
min             0.000000               0.000000            0.000000   
25%             0.000000               0.000000            0.000000   
50%             0.000000               0.000000            0.000000   
75%             9.900000              39.900000           19.900000   
max             9.900000              39.900000           19.900000   

       ValorMensal  
count  5984.000000  
mean    257.226237  
std     146.260736  
min      44.900000  
25%     149.900000  
50%     229.400000  
75%     344.600000  
max     699.400000

In [16]:
# moda dos elementos por categoria ( coluna )
dados2.mode() 

Genero Dependentes  MesesComoCliente ServicoTelefone  ValorTelefone  \
0  Masculino         Nao                 1             Sim           74.9   

  MultiplasLinhas ServicoInternet  ValorInternet ServicoSegurancaOnline  \
0             Nao           Fibra           94.9                    Nao   

   ValorSegurancaOnline  ... ServicoSuporteTecnico  ServicoStreamingTV  \
0                   0.0  ...                   Nao                 Nao   

  ValorServiçoStreaming ServicoFilmes ValorServicoFilmes  TipoContrato  \
0                   0.0           Nao                0.0        Mensal   

  FaturaDigital    FormaPagamento ValorMensal Churn  
0           Sim  BoletoEletronico        74.9   Nao  

[1 rows x 23 columns]

## Análise de outliers
--------------------------------------------------------------------------------


In [17]:
dados2.dtypes

Genero                     object
Dependentes                object
MesesComoCliente            int64
ServicoTelefone            object
ValorTelefone             float64
MultiplasLinhas            object
ServicoInternet            object
ValorInternet             float64
ServicoSegurancaOnline     object
ValorSegurancaOnline      float64
ServicoBackupOnline        object
ValorBackupOnline         float64
ProtecaoEquipamento        object
ServicoSuporteTecnico      object
ServicoStreamingTV         object
ValorServiçoStreaming     float64
ServicoFilmes              object
ValorServicoFilmes        float64
TipoContrato               object
FaturaDigital              object
FormaPagamento             object
ValorMensal               float64
Churn                      object
dtype: object

In [18]:
px.box ( dados2, y = "MesesComoCliente")

In [19]:
px.box ( dados2, y = "ValorTelefone")

In [20]:
px.box ( dados2, y = "ValorInternet")

In [21]:
px.box ( dados2, y = "ValorSegurancaOnline")

In [22]:
px.box ( dados2, y = "ValorBackupOnline")

In [23]:
px.box ( dados2, y = "ValorServiçoStreaming")

In [24]:
px.box ( dados2, y = "ValorServicoFilmes")

In [25]:
px.box ( dados2, y = "ValorMensal")

# Pré processamento
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


## Transformando as variáveis categóricas nominais em variáveis categóricas ordinais
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

In [26]:
dados2 ["Genero"].replace({"Feminino":0,"Masculino":1},inplace=True)
dados2 ["Dependentes"].replace({"Nao":0,"Sim":1},inplace=True)
dados2 ["ServicoTelefone"].replace({"Nao":0,"Sim":1},inplace=True)
dados2 ["MultiplasLinhas"].replace({"Nao":0,"Sim":1,"SemTelefone":2},inplace=True)
dados2 ["ServicoInternet"].replace({"Nao":0,"DSL":1,"Fibra":2},inplace=True)
dados2 ["ServicoSegurancaOnline"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoBackupOnline"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ProtecaoEquipamento"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoSuporteTecnico"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoStreamingTV"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoFilmes"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["TipoContrato"].replace({"Anual":0,"Mensal":1,"2 anos":2},inplace=True)
dados2 ["FaturaDigital"].replace({"Nao":0,"Sim":1},inplace=True)
dados2 ["FormaPagamento"].replace({"BoletoImpresso":0,"BoletoEletronico":1,"CartaoCredito":2,"DebitoAutomatico":3},inplace=True)
dados2 ["Churn"].replace({"Nao":0,"Sim":1},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [27]:
dados2.dtypes

Genero                      int64
Dependentes                 int64
MesesComoCliente            int64
ServicoTelefone             int64
ValorTelefone             float64
MultiplasLinhas             int64
ServicoInternet             int64
ValorInternet             float64
ServicoSegurancaOnline      int64
ValorSegurancaOnline      float64
ServicoBackupOnline         int64
ValorBackupOnline         float64
ProtecaoEquipamento         int64
ServicoSuporteTecnico       int64
ServicoStreamingTV          int64
ValorServiçoStreaming     float64
ServicoFilmes               int64
ValorServicoFilmes        float64
TipoContrato                int64
FaturaDigital               int64
FormaPagamento              int64
ValorMensal               float64
Churn                       int64
dtype: object

## Separando atributos previsores e alvo
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [28]:
dados2.shape

(5984, 23)

In [29]:
'''criando um array somente com os valores previsores ( dados relacionados aos serviços habilitados ) 
menos a ultima coluna, que indica se o cliente cancelou ou não'''
previsores=dados2.iloc[:,0:22].values

In [30]:
previsores

array([[  0. ,   1. ,   9. , ...,   1. ,   0. , 199.6],
       [  1. ,   0. ,   9. , ...,   0. ,   0. , 169.7],
       [  1. ,   0. ,   4. , ...,   1. ,   1. , 184.8],
       ...,
       [  1. ,   0. ,  22. , ...,   1. ,   1. , 214.7],
       [  1. ,   0. ,   2. , ...,   1. ,   0. , 149.7],
       [  1. ,   1. ,  67. , ...,   0. ,   0. , 169.6]])

In [31]:
# criando um array com os resultados alvo ( cliente cancelou ou não )
alvo = dados2.iloc[:,22].values 

In [32]:
alvo

array([0, 0, 1, ..., 1, 0, 0])

In [33]:
# Verificando a quantidade de linhas e colunas de previsores
previsores.shape 

(5984, 22)

In [34]:
# Verificando a quantidade de linhas de alvo ( só tem uma coluna que indica se o cliente cancelou ou não)
alvo.shape 

(5984,)

In [35]:
#Criando variáveis dummy com OneHotEncoder para anular possível hierarquia entre os dados
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

Parâmetros ColumnTransformer:

*   name: nome dado a transformação
*   transformer: tipo de estimador (OneHotEncoder)
*   columns: colunas que serão transformadas
*   remainder: o que acontecerá com os restantes das colunas não relacionadas:

1 - drop ( exclui as outras colunas )

2 - passthrough ( mantem as outras colunas )
Drop é Default

*   sparse_threshold: parâmetro de classificação de matrizes esparsas. Default é 0.3.
*   n_jobs: número de trabalhos a serem executados em paralelo. default é nenhum.
*   transformer_weights: definição de pesos aos transformadores.
*   verbose: default é False. se for True a execução é apresentada na tela.

In [36]:
previsores2 = ColumnTransformer(transformers=[('OneHot',OneHotEncoder(),[0,1,3,5,6,8,10,12,13,14,16,18,19,20])],remainder="passthrough").fit_transform(previsores)

In [37]:
previsores2

array([[  1. ,   0. ,   0. , ...,  39.9,   0. , 199.6],
       [  0. ,   1. ,   1. , ...,   0. ,  19.9, 169.7],
       [  0. ,   1. ,   1. , ...,   0. ,   0. , 184.8],
       ...,
       [  0. ,   1. ,   1. , ...,   0. ,  19.9, 214.7],
       [  0. ,   1. ,   1. , ...,   0. ,   0. , 149.7],
       [  0. ,   1. ,   0. , ...,   0. ,  19.9, 169.6]])

## Análise das escalas dos atributos
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
PADRONIZAÇÃO ( utiliza a média e o desvio padrão como referência )

NORMALIZAÇÃO ( utiliza os valores máximo e mínimo como referência )

In [38]:
# Estatística descritiva
dados2.describe() 

Genero  Dependentes  MesesComoCliente  ServicoTelefone  \
count  5984.000000  5984.000000       5984.000000      5984.000000   
mean      0.509525     0.299131         32.456551         0.901404   
std       0.499951     0.457916         24.511387         0.298144   
min       0.000000     0.000000          0.000000         0.000000   
25%       0.000000     0.000000          9.000000         1.000000   
50%       1.000000     0.000000         29.000000         1.000000   
75%       1.000000     1.000000         56.000000         1.000000   
max       1.000000     1.000000         72.000000         1.000000   

       ValorTelefone  MultiplasLinhas  ServicoInternet  ValorInternet  \
count     5984.00000      5984.000000      5984.000000    5984.000000   
mean        99.65752         0.622828         1.223429     128.135963   
std         68.38464         0.657403         0.777663     104.312756   
min          0.00000         0.000000         0.000000       0.000000   
25%         54.90000         0.000000         1.000000      94.900000   
50%         74.90000         1.000000         1.000000      94.900000   
75%        149.90000         1.000000         2.000000     149.900000   
max        299.90000         2.000000         2.000000     319.900000   

       ServicoSegurancaOnline  ValorSegurancaOnline  ...  \
count             5984.000000           5984.000000  ...   
mean                 0.717246              2.832353  ...   
std                  0.796279              4.474530  ...   
min                  0.000000              0.000000  ...   
25%                  0.000000              0.000000  ...   
50%                  1.000000              0.000000  ...   
75%                  1.000000              9.900000  ...   
max                  2.000000              9.900000  ...   

       ServicoSuporteTecnico  ServicoStreamingTV  ValorServiçoStreaming  \
count            5984.000000         5984.000000            5984.000000   
mean                0.720922            0.816344              15.369235   
std                 0.795266            0.762347              19.418602   
min                 0.000000            0.000000               0.000000   
25%                 0.000000            0.000000               0.000000   
50%                 1.000000            1.000000               0.000000   
75%                 1.000000            1.000000              39.900000   
max                 2.000000            2.000000              39.900000   

       ServicoFilmes  ValorServicoFilmes  TipoContrato  FaturaDigital  \
count    5984.000000         5984.000000   5984.000000    5984.000000   
mean        0.821858            7.775100      1.027239       0.589238   
std         0.760035            9.710204      0.673085       0.492013   
min         0.000000            0.000000      0.000000       0.000000   
25%         0.000000            0.000000      1.000000       0.000000   
50%         1.000000            0.000000      1.000000       1.000000   
75%         1.000000           19.900000      1.000000       1.000000   
max         2.000000           19.900000      2.000000       1.000000   

       FormaPagamento  ValorMensal        Churn  
count     5984.000000  5984.000000  5984.000000  
mean         1.425969   257.226237     0.265207  
std          1.067127   146.260736     0.441480  
min          0.000000    44.900000     0.000000  
25%          1.000000   149.900000     0.000000  
50%          1.000000   229.400000     0.000000  
75%          2.000000   344.600000     1.000000  
max          3.000000   699.400000     1.000000  

[8 rows x 23 columns]

In [39]:
# importando o SKLEARN e seu subpacote StandardScaler para fazer a conversão de escalas baseado em PADRONIZAÇÃO
from sklearn.preprocessing import StandardScaler

In [40]:
# Criando uma nova variavel para receber a conversão
previsores_esc = StandardScaler().fit_transform(previsores2)

In [41]:
previsores_esc 

array([[ 1.01923578, -1.01923578, -1.5306916 , ...,  1.26336671,
        -0.8007813 , -0.39402955],
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.79153582,
         1.24878041, -0.59847607],
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.79153582,
        -0.8007813 , -0.49522716],
       ...,
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.79153582,
         1.24878041, -0.29078064],
       [-0.98112726,  0.98112726,  0.65329946, ..., -0.79153582,
        -0.8007813 , -0.7352296 ],
       [-0.98112726,  0.98112726, -1.5306916 , ..., -0.79153582,
         1.24878041, -0.59915984]])

In [42]:
# Criando um dataframe para receber os dados escalonados
previsoresdf = pd.DataFrame(previsores_esc)

In [43]:
previsoresdf

0         1         2         3         4         5         6   \
0     1.019236 -1.019236 -1.530692  1.530692 -0.330728  0.330728  1.049696   
1    -0.981127  0.981127  0.653299 -0.653299 -0.330728  0.330728 -0.952657   
2    -0.981127  0.981127  0.653299 -0.653299 -0.330728  0.330728  1.049696   
3    -0.981127  0.981127  0.653299 -0.653299 -0.330728  0.330728  1.049696   
4     1.019236 -1.019236  0.653299 -0.653299 -0.330728  0.330728  1.049696   
...        ...       ...       ...       ...       ...       ...       ...   
5979  1.019236 -1.019236  0.653299 -0.653299 -0.330728  0.330728  1.049696   
5980  1.019236 -1.019236  0.653299 -0.653299 -0.330728  0.330728  1.049696   
5981 -0.981127  0.981127  0.653299 -0.653299 -0.330728  0.330728 -0.952657   
5982 -0.981127  0.981127  0.653299 -0.653299 -0.330728  0.330728  1.049696   
5983 -0.981127  0.981127 -1.530692  1.530692 -0.330728  0.330728  1.049696   

            7         8         9   ...        37        38        39  \
0    -0.860844 -0.330728 -0.524232  ... -0.527598 -0.528633 -0.957045   
1     1.161650 -0.330728 -0.524232  ... -0.527598 -0.528633 -0.957045   
2    -0.860844 -0.330728 -0.524232  ... -0.527598 -0.528633 -1.161049   
3    -0.860844 -0.330728 -0.524232  ... -0.527598 -0.528633 -0.793842   
4    -0.860844 -0.330728 -0.524232  ... -0.527598 -0.528633 -1.201850   
...        ...       ...       ...  ...       ...       ...       ...   
5979 -0.860844 -0.330728  1.907553  ... -0.527598  1.891672 -1.161049   
5980 -0.860844 -0.330728 -0.524232  ... -0.527598 -0.528633 -0.793842   
5981  1.161650 -0.330728 -0.524232  ... -0.527598 -0.528633 -0.426635   
5982 -0.860844 -0.330728 -0.524232  ... -0.527598 -0.528633 -1.242651   
5983 -0.860844 -0.330728 -0.524232  ... -0.527598 -0.528633  1.409399   

            40        41        42        43        44        45        46  
0    -0.654551 -0.318645 -0.633047  1.365477  1.263367 -0.800781 -0.394030  
1    -0.654551 -0.318645 -0.633047 -0.732345 -0.791536  1.248780 -0.598476  
2    -0.654551  0.016912 -0.633047 -0.732345 -0.791536 -0.800781 -0.495227  
3    -0.654551  0.016912 -0.633047  1.365477  1.263367  1.248780 -0.018641  
4    -0.654551  0.016912 -0.633047 -0.732345  1.263367 -0.800781 -0.222404  
...        ...       ...       ...       ...       ...       ...       ...  
5979 -0.800795 -1.228485 -0.633047 -0.732345 -0.791536 -0.800781 -1.451818  
5980 -0.800795 -0.318645  1.579660 -0.732345 -0.791536 -0.800781 -0.735230  
5981 -0.800795  0.208660 -0.633047 -0.732345 -0.791536  1.248780 -0.290781  
5982 -0.800795 -0.318645 -0.633047  1.365477 -0.791536 -0.800781 -0.735230  
5983 -0.800795 -0.318645  1.579660 -0.732345 -0.791536  1.248780 -0.599160  

[5984 rows x 47 columns]

In [44]:
previsoresdf.describe()

0             1             2             3             4   \
count  5.984000e+03  5.984000e+03  5.984000e+03  5.984000e+03  5.984000e+03   
mean   2.256068e-17 -2.256068e-17 -1.733610e-16  1.104286e-16 -6.174502e-17   
std    1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min   -9.811273e-01 -1.019236e+00 -1.530692e+00 -6.532995e-01 -3.307277e-01   
25%   -9.811273e-01 -1.019236e+00 -1.530692e+00 -6.532995e-01 -3.307277e-01   
50%   -9.811273e-01  9.811273e-01  6.532995e-01 -6.532995e-01 -3.307277e-01   
75%    1.019236e+00  9.811273e-01  6.532995e-01  1.530692e+00 -3.307277e-01   
max    1.019236e+00  9.811273e-01  6.532995e-01  1.530692e+00  3.023636e+00   

                 5             6             7             8             9   \
count  5.984000e+03  5.984000e+03  5.984000e+03  5.984000e+03  5.984000e+03   
mean   8.549311e-17 -5.699541e-17  7.124426e-18 -6.174502e-17 -4.274655e-17   
std    1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min   -3.023636e+00 -9.526568e-01 -8.608445e-01 -3.307277e-01 -5.242317e-01   
25%    3.307277e-01 -9.526568e-01 -8.608445e-01 -3.307277e-01 -5.242317e-01   
50%    3.307277e-01 -9.526568e-01 -8.608445e-01 -3.307277e-01 -5.242317e-01   
75%    3.307277e-01  1.049696e+00  1.161650e+00 -3.307277e-01 -5.242317e-01   
max    3.307277e-01  1.049696e+00  1.161650e+00  3.023636e+00  1.907553e+00   

       ...            37            38            39            40  \
count  ...  5.984000e+03  5.984000e+03  5.984000e+03  5.984000e+03   
mean   ... -3.562213e-18  1.424885e-17  1.187404e-16 -1.219512e-13   
std    ...  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min    ... -5.275977e-01 -5.286328e-01 -1.324252e+00 -1.457430e+00   
25%    ... -5.275977e-01 -5.286328e-01 -9.570454e-01 -6.545514e-01   
50%    ... -5.275977e-01 -5.286328e-01 -1.410300e-01 -3.620636e-01   
75%    ... -5.275977e-01 -5.286328e-01  9.605910e-01  7.347656e-01   
max    ...  1.895384e+00  1.891672e+00  1.613403e+00  2.928424e+00   

                 41            42            43            44            45  \
count  5.984000e+03  5.984000e+03  5.984000e+03  5.984000e+03  5.984000e+03   
mean  -1.075218e-13  1.283822e-14 -7.366656e-15  1.866956e-14 -3.427917e-14   
std    1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min   -1.228485e+00 -6.330474e-01 -7.323446e-01 -7.915358e-01 -8.007813e-01   
25%   -3.186450e-01 -6.330474e-01 -7.323446e-01 -7.915358e-01 -8.007813e-01   
50%   -3.186450e-01 -6.330474e-01 -7.323446e-01 -7.915358e-01 -8.007813e-01   
75%    2.086596e-01  1.579660e+00  1.365477e+00  1.263367e+00  1.248780e+00   
max    1.838510e+00  1.579660e+00  1.365477e+00  1.263367e+00  1.248780e+00   

                 46  
count  5.984000e+03  
mean   2.442253e-14  
std    1.000084e+00  
min   -1.451818e+00  
25%   -7.338621e-01  
50%   -1.902668e-01  
75%    5.974335e-01  
max    3.023441e+00  

[8 rows x 47 columns]

## Salvando as variáveis
--------------------------------------------------------------------------------


In [45]:
import pickle

In [46]:
# criando arquivo
arq1 = open("classchurn.pk1","wb")  # quando cria "wb", quando lê o arquivo "rb"

In [47]:
# salvando a variável no arquivo
pickle.dump(alvo, arq1)

In [48]:
# fechar arquivo
arq1.close()

In [49]:
# lendo o arquivo
arq1 = open("classchurn.pk1","rb")   

In [50]:
# chamando a variável
alvo = pickle.load(arq1)

In [51]:
alvo

array([0, 0, 1, ..., 1, 0, 0])

# Separando base de treino e base de teste
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [58]:
from sklearn.model_selection import train_test_split

Parâmetros do Train_Test_Split:

arrays : nomes dos atributos previsores e alvo
test_size : tamanho em porcentagem dos dados de teste. Default é none.
train_size : tamanho em porcentagem dos dados de treinamento. Default é none.
randon_state : nomeação de um estado aleatório
shuffle : embaralhamento dos dados aleatórios. Associado com random _state ocorre o mesmo embaralhamento sempre. Default é True.
stratify : possibilidade de dividir os dados de forma estratificada. Default é none. ( Nesse caso é mantida a proporção, isto é, se tem 30% de zeros e 70% de 1 no DataFrame, na separação em treinamento e teste se manterá essa proporção ).

In [59]:
# Separamos 30% dos dados para teste e 70% para treino
x_treino,x_teste,y_treino,y_teste = train_test_split(previsores_esc,alvo,test_size=0.3,random_state=0)

In [60]:
x_treino.shape

(4188, 47)

In [61]:
y_treino.shape

(4188,)

In [62]:
x_teste.shape

(1796, 47)

In [63]:
y_teste.shape

(1796,)

# Resultado dos Modelos:
================================================================================

1.  Naive Bayes : Acurácia Média: 72.49%  / previsores
2.  Máquina de vetores de suporte: Acurácia Média: 79.40%  / previsores_esc
3.  Regressão logística: Acurácia Média: 79.95% / previsores2
4.  KNN: Acurácia Média: 78.69% / previsores2
5.  Árvore de decisão: Acurácia Média: 78.23% / previsores2 
6.  XGBOOST: Acurácia Média: 80.25% / previsores_esc


# Naive Bayes
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

In [64]:
# Treinamento do algotitmo
from sklearn.naive_bayes import GaussianNB

In [65]:
naive = GaussianNB()

In [66]:
naive.fit(x_treino,y_treino)

GaussianNB()

In [67]:
previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([1, 1, 1, ..., 0, 1, 1])

In [68]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [69]:
accuracy_score(y_teste, previsoes_naive)

0.6893095768374164

In [70]:
confusion_matrix(y_teste,previsoes_naive)

array([[855, 485],
       [ 73, 383]])

In [71]:
print(classification_report(y_teste,previsoes_naive))

              precision    recall  f1-score   support

           0       0.92      0.64      0.75      1340
           1       0.44      0.84      0.58       456

    accuracy                           0.69      1796
   macro avg       0.68      0.74      0.67      1796
weighted avg       0.80      0.69      0.71      1796



## Analise de dados treino

In [72]:
previsoes_treino = naive.predict(x_treino)
previsoes_treino

array([0, 0, 1, ..., 1, 0, 0])

In [73]:
accuracy_score(y_treino,previsoes_treino)

0.6919770773638968

In [74]:
confusion_matrix(y_treino,previsoes_treino)

array([[1937, 1120],
       [ 170,  961]])

## Validação cruzada

In [75]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [76]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [77]:
# Criando o modelo
modelo = GaussianNB()
resultado = cross_val_score(modelo,previsores_esc,alvo,cv=kfold)

In [78]:
resultado

array([0.67      , 0.675     , 0.7       , 0.705     , 0.64      ,
       0.735     , 0.745     , 0.675     , 0.755     , 0.67      ,
       0.69      , 0.69      , 0.73      , 0.695     , 0.64824121,
       0.71356784, 0.73869347, 0.69346734, 0.69849246, 0.69849246,
       0.71356784, 0.69849246, 0.74371859, 0.69346734, 0.66331658,
       0.69849246, 0.64824121, 0.67336683, 0.69849246, 0.63819095])

In [79]:
# Usando a média e desvio padrão
print("Acurácia Média: %.2f%%" %(resultado.mean()*100))

Acurácia Média: 69.45%


# Maquina de vetores de suporte( SVM )
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [80]:
from sklearn.svm import SVC   # Importando a biblioteca SVM especifico para classificação ( SVC )

In [81]:
svm = SVC(kernel='rbf',random_state=1, C=2) # Cria o vetor "svm". A configuração kernel para transformar os dados para aplicação da forma correta
svm.fit(x_treino, y_treino)  # Criação do fit de treinamento

SVC(C=2, random_state=1)

In [82]:
previsoes_svm=svm.predict(x_teste)   # Criação do PREVISOR baseado no svm
previsoes_svm # Visualiza o resultado

array([0, 0, 1, ..., 0, 1, 0])

In [83]:
y_teste # Visualiza a base y de teste

array([0, 0, 0, ..., 0, 1, 1])

In [84]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm)*100.0))

Acurácia: 78.56%


In [85]:
confusion_matrix(y_teste, previsoes_svm)

array([[1197,  143],
       [ 242,  214]])

In [86]:
print(classification_report(y_teste, previsoes_svm))

              precision    recall  f1-score   support

           0       0.83      0.89      0.86      1340
           1       0.60      0.47      0.53       456

    accuracy                           0.79      1796
   macro avg       0.72      0.68      0.69      1796
weighted avg       0.77      0.79      0.78      1796



## Analise dados de treino
------------------------------------------------------------------------------

In [87]:
previsoes_treino = svm.predict(x_treino)
previsoes_treino

array([0, 0, 1, ..., 0, 0, 0])

In [88]:
accuracy_score(y_treino, previsoes_treino)

0.830945558739255

In [89]:
confusion_matrix(y_treino,previsoes_treino)

array([[2827,  230],
       [ 478,  653]])

## Validação Cruzada
-------------------------------------------------------------------------------

In [90]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [91]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [92]:
#Criando o modelo
modelo=SVC(kernel="rbf",random_state=1,C=2.0)
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)

In [93]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 79.40%


# Regressão Logistica
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------


In [94]:
from sklearn.linear_model import LogisticRegression   # Importando biblioteca LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [95]:
logistica = LogisticRegression(random_state=1,max_iter=200, penalty="l2", tol=0.0001,C=1,solver="lbfgs")
logistica.fit(x_treino,y_treino)

LogisticRegression(C=1, max_iter=200, random_state=1)

In [96]:
logistica.intercept_  # Verifica o resultado do Intercepto

array([-1.6007616])

In [97]:
logistica.coef_  # Verifica o resultado dos coefientes

array([[ 0.01441566, -0.01441566,  0.05360536, -0.05360536,  0.03121208,
        -0.03121208, -0.09561786,  0.07776053,  0.03121208, -0.04577513,
        -0.1974507 ,  0.22712144,  0.0713012 , -0.03723263, -0.04577513,
         0.04324587, -0.0054913 , -0.04577513,  0.04531297, -0.00774119,
        -0.04577513,  0.11364963, -0.0837591 , -0.04577513, -0.01423425,
         0.05300572, -0.04577513, -0.03264418,  0.07126889, -0.04577513,
        -0.01948348,  0.28026991, -0.30781828, -0.08823035,  0.08823035,
        -0.03344916,  0.11395539, -0.0629536 , -0.03331908, -0.82437904,
        -0.0178236 ,  0.02466996, -0.03723263, -0.0054913 ,  0.05300572,
         0.07126889,  0.01971375]])

In [98]:
previsoes_logistica = logistica.predict(x_teste)
previsoes_logistica

array([0, 0, 0, ..., 0, 0, 0])

In [99]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste,previsoes_logistica)*100))

Acurácia: 78.84%


In [100]:
confusion_matrix(y_teste,previsoes_logistica)

array([[1182,  158],
       [ 222,  234]])

In [101]:
print(classification_report(y_teste,previsoes_logistica))

              precision    recall  f1-score   support

           0       0.84      0.88      0.86      1340
           1       0.60      0.51      0.55       456

    accuracy                           0.79      1796
   macro avg       0.72      0.70      0.71      1796
weighted avg       0.78      0.79      0.78      1796



## Analise dados de treino

In [102]:
previsoes_treino= logistica.predict(x_treino)   # Criando Dataframe para receber dados treino
previsoes_treino

array([0, 0, 1, ..., 0, 0, 0])

In [103]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))   # Verifica a acurácio da base treino

Acurácia: 80.49%


In [104]:
confusion_matrix(y_treino,previsoes_treino)

array([[2751,  306],
       [ 511,  620]])

In [105]:
print(classification_report(y_treino,previsoes_treino))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      3057
           1       0.67      0.55      0.60      1131

    accuracy                           0.80      4188
   macro avg       0.76      0.72      0.74      4188
weighted avg       0.80      0.80      0.80      4188



## Validação Cruzada

In [106]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [107]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [108]:
#Criando o modelo
modelo=LogisticRegression(random_state=1,max_iter=200, penalty="l2", tol=0.0001,C=1,solver="lbfgs")
resultado=cross_val_score(modelo, previsores,alvo,cv=kfold)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression

/usr/local/lib/python3.7/dist-packages/sklearn/lin

In [109]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 79.60%


# K NN - K vizinhos mais proximos
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [110]:
from sklearn.neighbors import KNeighborsClassifier   # Importando a biblioteca

In [111]:
knn = KNeighborsClassifier(n_neighbors=10, metric='minkowski',p=2)  #configurando o KNN
knn.fit(x_treino,y_treino)   # Criando o modelo de treino

KNeighborsClassifier(n_neighbors=10)

In [112]:
previsoes_knn = knn.predict(x_teste)
previsoes_knn

array([1, 0, 1, ..., 0, 1, 0])

In [113]:
print("Acuracia: %.2f%%" % (accuracy_score(y_teste,previsoes_knn)*100))

Acuracia: 76.67%


In [114]:
confusion_matrix(y_teste,previsoes_knn)

array([[1165,  175],
       [ 244,  212]])

In [115]:
print(classification_report(y_teste,previsoes_knn))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1340
           1       0.55      0.46      0.50       456

    accuracy                           0.77      1796
   macro avg       0.69      0.67      0.68      1796
weighted avg       0.76      0.77      0.76      1796



## Analise do treino

In [116]:
previsoes_treino= knn.predict(x_treino)   # Criando Dataframe para receber dados treino
previsoes_treino

array([0, 0, 1, ..., 0, 0, 0])

In [117]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))   # Verifica a acurácio da base treino

Acurácia: 81.21%


In [118]:
confusion_matrix(y_teste,previsoes_knn)

array([[1165,  175],
       [ 244,  212]])

In [119]:
print(classification_report(y_teste,previsoes_knn))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85      1340
           1       0.55      0.46      0.50       456

    accuracy                           0.77      1796
   macro avg       0.69      0.67      0.68      1796
weighted avg       0.76      0.77      0.76      1796



## Validação cruzada

In [120]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [121]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [122]:
#Criando o modelo
modelo=KNeighborsClassifier(n_neighbors=10, metric='minkowski',p=1)
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)

In [123]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 77.59%


# Árvore de decisão
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [124]:
from sklearn.tree import DecisionTreeClassifier

In [125]:
arvore = DecisionTreeClassifier(criterion='entropy', random_state=0,max_depth=3)
arvore.fit(x_treino,y_treino)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [126]:
previsoes_arvore = arvore.predict(x_teste)
previsoes_arvore

array([0, 0, 0, ..., 0, 0, 0])

In [127]:
y_teste

array([0, 0, 0, ..., 0, 1, 1])

In [128]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste,previsoes_arvore)*100))

Acurácia: 78.40%


In [129]:
confusion_matrix(y_teste,previsoes_arvore)

array([[1242,   98],
       [ 290,  166]])

In [130]:
print(classification_report(y_teste,previsoes_arvore))

              precision    recall  f1-score   support

           0       0.81      0.93      0.86      1340
           1       0.63      0.36      0.46       456

    accuracy                           0.78      1796
   macro avg       0.72      0.65      0.66      1796
weighted avg       0.76      0.78      0.76      1796



## Analise de treino

In [131]:
previsoes_treino=arvore.predict(x_treino)
previsoes_treino

array([0, 0, 1, ..., 0, 0, 0])

In [132]:
accuracy_score(y_treino,previsoes_treino)

0.7920248328557784

In [133]:
confusion_matrix(y_treino,previsoes_treino)

array([[2869,  188],
       [ 683,  448]])

## Validação Cruzada

In [134]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [135]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [136]:
#Criando o modelo
modelo=DecisionTreeClassifier(criterion='entropy',random_state=0,max_depth=3)
resultado=cross_val_score(modelo, previsores,alvo,cv=kfold)

In [137]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 77.81%


# XGBOOST
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [138]:
from xgboost import XGBClassifier

In [139]:
xg=XGBClassifier(max_depth=2,learning_rate=0.1,n_estimators=150,objective='binary:logistic',random_state=3)
xg.fit(x_treino, y_treino)

XGBClassifier(max_depth=2, n_estimators=150, random_state=3)

In [140]:
previsoes_xg = xg.predict(x_teste)
previsoes_xg 

array([0, 0, 0, ..., 0, 0, 1])

In [141]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_teste,previsoes_xg)*100))

Acurácia: 79.62%


In [142]:
confusion_matrix(y_teste,previsoes_xg)

array([[1200,  140],
       [ 226,  230]])

In [143]:
print(classification_report(y_teste,previsoes_xg))

              precision    recall  f1-score   support

           0       0.84      0.90      0.87      1340
           1       0.62      0.50      0.56       456

    accuracy                           0.80      1796
   macro avg       0.73      0.70      0.71      1796
weighted avg       0.79      0.80      0.79      1796



## Analise de treino

In [144]:
previsoes_treino=xg.predict(x_treino)
previsoes_treino

array([0, 0, 1, ..., 0, 0, 0])

In [145]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_treino,previsoes_treino)*100))

Acurácia: 81.66%


In [146]:
confusion_matrix(y_treino,previsoes_treino)

array([[2792,  265],
       [ 503,  628]])

In [147]:
print(classification_report(y_treino,previsoes_treino))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      3057
           1       0.70      0.56      0.62      1131

    accuracy                           0.82      4188
   macro avg       0.78      0.73      0.75      4188
weighted avg       0.81      0.82      0.81      4188



## Validação cruzada

In [148]:
from sklearn.model_selection import KFold		
from sklearn.model_selection import cross_val_score		
kfold = KFold(n_splits=30, shuffle=True, random_state=5)		
modelo=XGBClassifier(max_depth=2,learning_rate=0.1,n_estimators=200,objective='binary:logistic',random_state=3)		
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)		
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))	

 A Acurácia Média: 80.25%


# CATBOOST
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [149]:
# iNSTALAÇÃO
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 1.2 MB/s 


In [150]:
from catboost import CatBoostClassifier

In [151]:
dados

Genero Dependentes  MesesComoCliente ServicoTelefone  ValorTelefone  \
0      Feminino         Sim                 9             Sim           54.9   
1     Masculino         Nao                 9             Sim           54.9   
2     Masculino         Nao                 4             Sim           54.9   
3     Masculino         Nao                13             Sim           54.9   
4      Feminino         Nao                 3             Sim           54.9   
...         ...         ...               ...             ...            ...   
5981   Feminino         Nao                 4             Sim           44.9   
5982   Feminino         Nao                13             Sim           44.9   
5983  Masculino         Nao                22             Sim           44.9   
5984  Masculino         Nao                 2             Sim           44.9   
5985  Masculino         Sim                67             Sim           44.9   

     MultiplasLinhas ServicoInternet  ValorInternet ServicoSegurancaOnline  \
0                Nao             DSL           94.9                    Nao   
1                Sim             DSL           94.9                    Nao   
2                Nao           Fibra          129.9                    Nao   
3                Nao           Fibra          129.9                    Nao   
4                Nao           Fibra          129.9                    Nao   
...              ...             ...            ...                    ...   
5981             Nao             Nao            0.0            SemInternet   
5982             Nao             DSL           94.9                    Sim   
5983             Sim           Fibra          149.9                    Nao   
5984             Nao             DSL           94.9                    Nao   
5985             Nao             DSL           94.9                    Sim   

      ValorSegurancaOnline  ... ServicoSuporteTecnico  ServicoStreamingTV  \
0                      0.0  ...                   Sim                 Sim   
1                      0.0  ...                   Nao                 Nao   
2                      0.0  ...                   Nao                 Nao   
3                      0.0  ...                   Nao                 Sim   
4                      0.0  ...                   Sim                 Sim   
...                    ...  ...                   ...                 ...   
5981                   0.0  ...           SemInternet         SemInternet   
5982                   9.9  ...                   Sim                 Nao   
5983                   0.0  ...                   Nao                 Nao   
5984                   0.0  ...                   Nao                 Nao   
5985                   9.9  ...                   Sim                 Nao   

     ValorServiçoStreaming ServicoFilmes ValorServicoFilmes  TipoContrato  \
0                     39.9           Nao                0.0         Anual   
1                      0.0           Sim               19.9        Mensal   
2                      0.0           Nao                0.0        Mensal   
3                     39.9           Sim               19.9        Mensal   
4                     39.9           Nao                0.0        Mensal   
...                    ...           ...                ...           ...   
5981                   0.0   SemInternet                0.0        Mensal   
5982                   0.0           Nao                0.0         Anual   
5983                   0.0           Sim               19.9        Mensal   
5984                   0.0           Nao                0.0        Mensal   
5985                   0.0           Sim               19.9        2 anos   

     FaturaDigital    FormaPagamento ValorMensal Churn  
0              Sim    BoletoImpresso       199.6   Nao  
1              Nao    BoletoImpresso       169.7   Nao  
2              Sim  BoletoEletronico       184.8   Sim  
3              Sim  BoletoEletron

In [152]:
dados3 = dados.dropna() 
dados3 ["Churn"].replace({"Nao":0,"Sim":1},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [153]:
previsores_cat= dados3.iloc[:,0:22]

In [154]:
alvo_cat= dados3.iloc[:,22]

In [155]:
alvo_cat.head()

0    0
1    0
2    1
3    1
4    1
Name: Churn, dtype: int64

In [156]:
previsores_cat.head()

Genero Dependentes  MesesComoCliente ServicoTelefone  ValorTelefone  \
0   Feminino         Sim                 9             Sim           54.9   
1  Masculino         Nao                 9             Sim           54.9   
2  Masculino         Nao                 4             Sim           54.9   
3  Masculino         Nao                13             Sim           54.9   
4   Feminino         Nao                 3             Sim           54.9   

  MultiplasLinhas ServicoInternet  ValorInternet ServicoSegurancaOnline  \
0             Nao             DSL           94.9                    Nao   
1             Sim             DSL           94.9                    Nao   
2             Nao           Fibra          129.9                    Nao   
3             Nao           Fibra          129.9                    Nao   
4             Nao           Fibra          129.9                    Nao   

   ValorSegurancaOnline  ... ProtecaoEquipamento  ServicoSuporteTecnico  \
0                   0.0  ...                 Nao                    Sim   
1                   0.0  ...                 Nao                    Nao   
2                   0.0  ...                 Sim                    Nao   
3                   0.0  ...                 Sim                    Nao   
4                   0.0  ...                 Nao                    Sim   

  ServicoStreamingTV ValorServiçoStreaming ServicoFilmes  ValorServicoFilmes  \
0                Sim                  39.9           Nao                 0.0   
1                Nao                   0.0           Sim                19.9   
2                Nao                   0.0           Nao                 0.0   
3                Sim                  39.9           Sim                19.9   
4                Sim                  39.9           Nao                 0.0   

  TipoContrato  FaturaDigital    FormaPagamento ValorMensal  
0        Anual            Sim    BoletoImpresso       199.6  
1       Mensal            Nao    BoletoImpresso       169.7  
2       Mensal            Sim  BoletoEletronico       184.8  
3       Mensal            Sim  BoletoEletronico       254.5  
4       Mensal            Sim    BoletoImpresso       224.7  

[5 rows x 22 columns]

In [157]:
from sklearn.model_selection import train_test_split

In [158]:
x_treino,x_teste,y_treino,y_teste = train_test_split(previsores_cat,alvo_cat,test_size=0.3,random_state=0)

In [159]:
categoricas=["Genero",
             "Dependentes",
             "ServicoTelefone",
             "MultiplasLinhas",
             "ServicoInternet",
             "ServicoSegurancaOnline",
             "ServicoBackupOnline",
             "ProtecaoEquipamento",
             "ServicoSuporteTecnico",
             "ServicoStreamingTV",
             "ServicoFilmes",
             "TipoContrato",
             "FaturaDigital",
             "FormaPagamento"
             ]

In [160]:
catboost= CatBoostClassifier(task_type='CPU',iterations=300, learning_rate=0.05,depth=5,random_state=5,eval_metric='Accuracy')

In [161]:
catboost.fit(x_treino,y_treino,cat_features=categoricas,plot=True,eval_set=(x_teste,y_teste))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.7891595	test: 0.7789532	best: 0.7789532 (0)	total: 69.1ms	remaining: 20.7s
1:	learn: 0.7889207	test: 0.7811804	best: 0.7811804 (1)	total: 94.5ms	remaining: 14.1s
2:	learn: 0.7898758	test: 0.7806236	best: 0.7811804 (1)	total: 134ms	remaining: 13.3s
3:	learn: 0.7901146	test: 0.7811804	best: 0.7811804 (1)	total: 159ms	remaining: 11.8s
4:	learn: 0.7951289	test: 0.7867483	best: 0.7867483 (4)	total: 181ms	remaining: 10.7s
5:	learn: 0.7982330	test: 0.7873051	best: 0.7873051 (5)	total: 194ms	remaining: 9.5s
6:	learn: 0.7996657	test: 0.7845212	best: 0.7873051 (5)	total: 208ms	remaining: 8.7s
7:	learn: 0.8034862	test: 0.7845212	best: 0.7873051 (5)	total: 221ms	remaining: 8.06s
8:	learn: 0.8032474	test: 0.7828508	best: 0.7873051 (5)	total: 234ms	remaining: 7.55s
9:	learn: 0.8015759	test: 0.7822940	best: 0.7873051 (5)	total: 241ms	remaining: 6.99s
10:	learn: 0.8010984	test: 0.7822940	best: 0.7873051 (5)	total: 253ms	remaining: 6.64s
11:	learn: 0.8020535	test: 0.7817372	best: 0.7873051 

In [162]:
previsoes_cat = catboost.predict(x_teste)
previsoes_cat

array([0, 0, 0, ..., 0, 0, 1])

In [163]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_teste,previsoes_cat)*100))

Acurácia: 80.29%


In [164]:
confusion_matrix(y_teste,previsoes_cat)

array([[1218,  122],
       [ 232,  224]])

## Analise dados Treino

In [165]:
previsoes_treino = catboost.predict(x_treino)
previsoes_treino

array([0, 0, 1, ..., 0, 0, 0])

In [166]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_treino,previsoes_treino)*100))

Acurácia: 82.55%


In [167]:
confusion_matrix(y_treino,previsoes_treino)

array([[2843,  214],
       [ 517,  614]])

## VALIDAÇÃO CRUZADA

In [168]:
from sklearn.model_selection import KFold		
from sklearn.model_selection import cross_val_score		
kfold = KFold(n_splits=30, shuffle=True, random_state=5)		
modelo=CatBoostClassifier(task_type='CPU',iterations=100, learning_rate=0.1,depth=8,random_state=8,eval_metric='Accuracy')		
resultado=cross_val_score(modelo, previsores,alvo,cv=kfold)		
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

0:	learn: 0.8001383	total: 52.1ms	remaining: 5.16s
1:	learn: 0.7999654	total: 89.6ms	remaining: 4.39s
2:	learn: 0.8020401	total: 134ms	remaining: 4.32s
3:	learn: 0.7999654	total: 163ms	remaining: 3.9s
4:	learn: 0.8027317	total: 171ms	remaining: 3.26s
5:	learn: 0.8011757	total: 191ms	remaining: 3s
6:	learn: 0.8035961	total: 220ms	remaining: 2.92s
7:	learn: 0.8041148	total: 252ms	remaining: 2.9s
8:	learn: 0.8101660	total: 297ms	remaining: 3s
9:	learn: 0.8129322	total: 332ms	remaining: 2.99s
10:	learn: 0.8122407	total: 372ms	remaining: 3.01s
11:	learn: 0.8132780	total: 411ms	remaining: 3.02s
12:	learn: 0.8146611	total: 460ms	remaining: 3.08s
13:	learn: 0.8163900	total: 528ms	remaining: 3.24s
14:	learn: 0.8181189	total: 587ms	remaining: 3.32s
15:	learn: 0.8182918	total: 615ms	remaining: 3.23s
16:	learn: 0.8189834	total: 647ms	remaining: 3.16s
17:	learn: 0.8184647	total: 737ms	remaining: 3.36s
18:	learn: 0.8184647	total: 756ms	remaining: 3.22s
19:	learn: 0.8195021	total: 778ms	remaining: 3.

In [169]:
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 79.28%
