<a href="https://colab.research.google.com/github/mauricionoronha/MLChurn/blob/main/Classifica%C3%A7%C3%A3o_CHURN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Carregando bibliotecas e arquivos
-------------------------------------------------------------
-------------------------------------------------------------


In [43]:
#Importando bibliotecas
import numpy as np		
import pandas as pd		
import plotly.express as px																				

## Importando os dados e fazendo verificações iniciais
-------------------------------------------------------------

In [44]:
dados = pd.read_csv("/content/drive/MyDrive/MACHINE_LEARNNING/telecom_users1.csv",sep=";",encoding="iso-8859-1")		

In [45]:
dados.head()

IDCliente     Genero  MesesComoCliente ServicoTelefone ServicoInternet  \
0  0002-ORFBO   Feminino                 9             Sim             DSL   
1  0003-MKNFE  Masculino                 9             Sim             DSL   
2  0004-TLHLJ  Masculino                 4             Sim           Fibra   
3  0011-IGKFF  Masculino                13             Sim           Fibra   
4  0013-EXCHZ   Feminino                 3             Sim           Fibra   

  ServicoSegurancaOnline ServicoBackupOnline ProtecaoEquipamento  \
0                    Nao                 Sim                 Nao   
1                    Nao                 Nao                 Nao   
2                    Nao                 Nao                 Sim   
3                    Nao                 Sim                 Sim   
4                    Nao                 Nao                 Nao   

  ServicoSuporteTecnico ServicoStreamingTV ServicoFilmes TipoContrato  \
0                   Sim                Sim           Nao        Anual   
1                   Nao                Nao           Sim       Mensal   
2                   Nao                Nao           Nao       Mensal   
3                   Nao                Sim           Sim       Mensal   
4                   Sim                Sim           Nao       Mensal   

  FaturaDigital    FormaPagamento ValorMensal Churn  
0           Sim    BoletoImpresso       199,6   Nao  
1           Nao    BoletoImpresso       169,7   Nao  
2           Sim  BoletoEletronico       184,8   Sim  
3           Sim  BoletoEletronico       254,5   Sim  
4           Sim    BoletoImpresso       224,7   Sim

In [46]:
dados=dados.drop(["IDCliente"],axis=1 )		# Eliminando a coluna IDCliente

# Análise dos dados
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

## Análise das variáveis
--------------------------------------------------------------------------------


In [47]:
dados.dtypes  # Visualizando o tipo de dado por coluna

Genero                    object
MesesComoCliente           int64
ServicoTelefone           object
ServicoInternet           object
ServicoSegurancaOnline    object
ServicoBackupOnline       object
ProtecaoEquipamento       object
ServicoSuporteTecnico     object
ServicoStreamingTV        object
ServicoFilmes             object
TipoContrato              object
FaturaDigital             object
FormaPagamento            object
ValorMensal               object
Churn                     object
dtype: object

In [48]:
dados["Genero"].value_counts()  # Contabilizando clientes masculinos e femininos

Masculino    3050
Feminino     2936
Name: Genero, dtype: int64

In [49]:
# Contabilizando cancelamentos
display(dados["Churn"].value_counts(normalize=True).map("{:.1%}".format))

Nao    73.5%
Sim    26.5%
Name: Churn, dtype: object

In [50]:
# Contabilizando formas de pagamento
display(dados["FormaPagamento"].value_counts(normalize=True).map("{:.1%}".format))

BoletoEletronico    33.5%
BoletoImpresso      22.9%
DebitoAutomatico    21.9%
CartaoCredito       21.8%
Name: FormaPagamento, dtype: object

In [51]:
display(dados["FaturaDigital"].value_counts(normalize=True).map("{:.1%}".format))

Sim    58.9%
Nao    41.1%
Name: FaturaDigital, dtype: object

## Verificando e corrigindo valores nulos ( NAN )
-------------------------------------------------------------



In [52]:
# Relação de quantidade
dados.isnull().sum()  # Soma por categoria ( coluna ) todos os valores nulos ( NAN )

Genero                    0
MesesComoCliente          0
ServicoTelefone           0
ServicoInternet           0
ServicoSegurancaOnline    0
ServicoBackupOnline       0
ProtecaoEquipamento       0
ServicoSuporteTecnico     0
ServicoStreamingTV        0
ServicoFilmes             0
TipoContrato              0
FaturaDigital             0
FormaPagamento            0
ValorMensal               0
Churn                     1
dtype: int64

In [53]:
# Eliminando dados NAN ( quantidade:1, insignificante para o modelo)
dados2 = dados.dropna() # Criando novo dataframe para mantar a integridade do dataframe original

In [54]:
dados2.isnull().sum() 

Genero                    0
MesesComoCliente          0
ServicoTelefone           0
ServicoInternet           0
ServicoSegurancaOnline    0
ServicoBackupOnline       0
ProtecaoEquipamento       0
ServicoSuporteTecnico     0
ServicoStreamingTV        0
ServicoFilmes             0
TipoContrato              0
FaturaDigital             0
FormaPagamento            0
ValorMensal               0
Churn                     0
dtype: int64

## Criando gráficos com as variáveis ( colunas )
-------------------------------------------------------------


In [55]:
# Criando histogramas com Plotly para verificar a relação entre as categorias e o cancelamento ( CHURN )
for coluna in dados2:      
        fig = px.histogram(dados2, x=coluna,nbins=60, color="Churn")
        fig.show()

## Análise estatística descritiva
-------------------------------------------------------------

In [56]:
# moda dos elementos por categoria ( coluna )
dados2.mode() 

Genero  MesesComoCliente ServicoTelefone ServicoInternet  \
0  Masculino                 1             Sim           Fibra   

  ServicoSegurancaOnline ServicoBackupOnline ProtecaoEquipamento  \
0                    Nao                 Nao                 Nao   

  ServicoSuporteTecnico ServicoStreamingTV ServicoFilmes TipoContrato  \
0                   Nao                Nao           Nao       Mensal   

  FaturaDigital    FormaPagamento ValorMensal Churn  
0           Sim  BoletoEletronico        74,9   Nao

## Análise de outliers
--------------------------------------------------------------------------------


In [57]:
dados2.dtypes

Genero                    object
MesesComoCliente           int64
ServicoTelefone           object
ServicoInternet           object
ServicoSegurancaOnline    object
ServicoBackupOnline       object
ProtecaoEquipamento       object
ServicoSuporteTecnico     object
ServicoStreamingTV        object
ServicoFilmes             object
TipoContrato              object
FaturaDigital             object
FormaPagamento            object
ValorMensal               object
Churn                     object
dtype: object

In [58]:
px.box ( dados2, y = "MesesComoCliente")

In [59]:
px.box ( dados2, y = "ValorMensal")

# Pré processamento
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


## Transformando as variáveis categóricas nominais em variáveis categóricas ordinais
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

In [60]:
dados2 ["Genero"].replace({"Feminino":0,"Masculino":1},inplace=True)
dados2 ["ServicoTelefone"].replace({"Nao":0,"Sim":1},inplace=True)
dados2 ["ServicoInternet"].replace({"Nao":0,"DSL":1,"Fibra":2},inplace=True)
dados2 ["ServicoSegurancaOnline"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoBackupOnline"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ProtecaoEquipamento"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoSuporteTecnico"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoStreamingTV"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["ServicoFilmes"].replace({"Nao":0,"Sim":1,"SemInternet":2},inplace=True)
dados2 ["TipoContrato"].replace({"Anual":0,"Mensal":1,"2 anos":2},inplace=True)
dados2 ["FaturaDigital"].replace({"Nao":0,"Sim":1},inplace=True)
dados2 ["FormaPagamento"].replace({"BoletoImpresso":0,"BoletoEletronico":1,"CartaoCredito":2,"DebitoAutomatico":3},inplace=True)
dados2 ["Churn"].replace({"Nao":0,"Sim":1},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [61]:
dados2.dtypes

Genero                     int64
MesesComoCliente           int64
ServicoTelefone            int64
ServicoInternet            int64
ServicoSegurancaOnline     int64
ServicoBackupOnline        int64
ProtecaoEquipamento        int64
ServicoSuporteTecnico      int64
ServicoStreamingTV         int64
ServicoFilmes              int64
TipoContrato               int64
FaturaDigital              int64
FormaPagamento             int64
ValorMensal               object
Churn                      int64
dtype: object

A coluna Valor Mensal aparece como object ( string ) porque as casas decimais referentes aos centavos estão separadas por vírgulas e o correto seria a separação por ponto.

Para corrigir devemos alterar no dataframe todos os valores separados por vírgula por ponto.

Em seguida será possivel alterar o tipo de dado de object ( string ) para float.

In [62]:
# Alterando vírgula por ponto 
dados2['ValorMensal'] = dados2['ValorMensal'].str.replace(',','.')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [63]:
# Alterando o tipo de dado de object ( string ) para float
dados2['ValorMensal'] = dados2['ValorMensal'] .astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [64]:
dados2.dtypes

Genero                      int64
MesesComoCliente            int64
ServicoTelefone             int64
ServicoInternet             int64
ServicoSegurancaOnline      int64
ServicoBackupOnline         int64
ProtecaoEquipamento         int64
ServicoSuporteTecnico       int64
ServicoStreamingTV          int64
ServicoFilmes               int64
TipoContrato                int64
FaturaDigital               int64
FormaPagamento              int64
ValorMensal               float64
Churn                       int64
dtype: object

## Separando atributos previsores e alvo
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [65]:
dados2.shape

(5985, 15)

In [68]:
'''criando um array somente com os valores previsores ( dados relacionados aos serviços habilitados ) 
menos a ultima coluna, que indica se o cliente cancelou ou não'''
previsores=dados2.iloc[:,0:14].values

In [69]:
previsores

array([[  0. ,   9. ,   1. , ...,   1. ,   0. , 199.6],
       [  1. ,   9. ,   1. , ...,   0. ,   0. , 169.7],
       [  1. ,   4. ,   1. , ...,   1. ,   1. , 184.8],
       ...,
       [  1. ,  22. ,   1. , ...,   1. ,   1. , 214.7],
       [  1. ,   2. ,   1. , ...,   1. ,   0. , 149.7],
       [  1. ,  67. ,   1. , ...,   0. ,   0. , 169.6]])

In [70]:
# criando um array com os resultados alvo ( cliente cancelou ou não )
alvo = dados2.iloc[:,14].values 

In [71]:
alvo

array([0, 0, 1, ..., 1, 0, 0])

In [72]:
# Verificando a quantidade de linhas e colunas de previsores
previsores.shape 

(5985, 14)

In [73]:
# Verificando a quantidade de linhas de alvo ( só tem uma coluna que indica se o cliente cancelou ou não)
alvo.shape 

(5985,)

In [74]:
#Criando variáveis dummy com OneHotEncoder para anular possível hierarquia entre os dados
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

Parâmetros ColumnTransformer:

*   name: nome dado a transformação
*   transformer: tipo de estimador (OneHotEncoder)
*   columns: colunas que serão transformadas
*   remainder: o que acontecerá com os restantes das colunas não relacionadas:

1 - drop ( exclui as outras colunas )

2 - passthrough ( mantem as outras colunas )
Drop é Default

*   sparse_threshold: parâmetro de classificação de matrizes esparsas. Default é 0.3.
*   n_jobs: número de trabalhos a serem executados em paralelo. default é nenhum.
*   transformer_weights: definição de pesos aos transformadores.
*   verbose: default é False. se for True a execução é apresentada na tela.

In [81]:
previsores2 = ColumnTransformer(transformers=[('OneHot',OneHotEncoder(),[0,2,3,4,5,6,7,8,9,10,11,12])],remainder="passthrough").fit_transform(previsores)

In [82]:
previsores2

array([[  1. ,   0. ,   0. , ...,   0. ,   9. , 199.6],
       [  0. ,   1. ,   0. , ...,   0. ,   9. , 169.7],
       [  0. ,   1. ,   0. , ...,   0. ,   4. , 184.8],
       ...,
       [  0. ,   1. ,   0. , ...,   0. ,  22. , 214.7],
       [  0. ,   1. ,   0. , ...,   0. ,   2. , 149.7],
       [  0. ,   1. ,   0. , ...,   0. ,  67. , 169.6]])

## Análise das escalas dos atributos
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
PADRONIZAÇÃO ( utiliza a média e o desvio padrão como referência )

NORMALIZAÇÃO ( utiliza os valores máximo e mínimo como referência )

In [83]:
# Estatística descritiva
dados2.describe() 

Genero  MesesComoCliente  ServicoTelefone  ServicoInternet  \
count  5985.000000       5985.000000      5985.000000      5985.000000   
mean      0.509440         32.462657         0.901420         1.223225   
std       0.499953         24.513890         0.298122         0.777759   
min       0.000000          0.000000         0.000000         0.000000   
25%       0.000000          9.000000         1.000000         1.000000   
50%       1.000000         29.000000         1.000000         1.000000   
75%       1.000000         56.000000         1.000000         2.000000   
max       1.000000         72.000000         1.000000         2.000000   

       ServicoSegurancaOnline  ServicoBackupOnline  ProtecaoEquipamento  \
count             5985.000000          5985.000000          5985.000000   
mean                 0.717460             0.780451             0.774603   
std                  0.796385             0.776440             0.778528   
min                  0.000000             0.000000             0.000000   
25%                  0.000000             0.000000             0.000000   
50%                  1.000000             1.000000             1.000000   
75%                  1.000000             1.000000             1.000000   
max                  2.000000             2.000000             2.000000   

       ServicoSuporteTecnico  ServicoStreamingTV  ServicoFilmes  TipoContrato  \
count            5985.000000         5985.000000    5985.000000   5985.000000   
mean                0.721136            0.816541       0.822055      1.027402   
std                 0.795372            0.762437       0.760124      0.673146   
min                 0.000000            0.000000       0.000000      0.000000   
25%                 0.000000            0.000000       0.000000      1.000000   
50%                 1.000000            1.000000       1.000000      1.000000   
75%                 1.000000            1.000000       1.000000      1.000000   
max                 2.000000            2.000000       2.000000      2.000000   

       FaturaDigital  FormaPagamento  ValorMensal        Churn  
count    5985.000000     5985.000000  5985.000000  5985.000000  
mean        0.589307        1.426232   257.216658     0.265163  
std         0.492001        1.067232   146.250391     0.441457  
min         0.000000        0.000000    44.900000     0.000000  
25%         0.000000        1.000000   149.900000     0.000000  
50%         1.000000        1.000000   229.400000     0.000000  
75%         1.000000        2.000000   344.600000     1.000000  
max         1.000000        3.000000   699.400000     1.000000

In [187]:
# importando o SKLEARN e seu subpacote StandardScaler para fazer a conversão de escalas baseado em PADRONIZAÇÃO
from sklearn.preprocessing import StandardScaler

In [188]:
# Criando uma nova variavel para receber a conversão
previsores_esc = StandardScaler().fit_transform(previsores2)

In [189]:
previsores_esc 

array([[ 1.01906219, -1.01906219, -0.33069702, ..., -0.528835  ,
        -0.9571968 , -0.39399192],
       [-0.98129438,  0.98129438, -0.33069702, ..., -0.528835  ,
        -0.9571968 , -0.5984529 ],
       [-0.98129438,  0.98129438, -0.33069702, ..., -0.528835  ,
        -1.16117984, -0.49519668],
       ...,
       [-0.98129438,  0.98129438, -0.33069702, ..., -0.528835  ,
        -0.4268409 , -0.29073571],
       [-0.98129438,  0.98129438, -0.33069702, ..., -0.528835  ,
        -1.24277306, -0.73521609],
       [-0.98129438,  0.98129438, -0.33069702, ..., -0.528835  ,
         1.40900645, -0.59913671]])

In [87]:
# Criando um dataframe para receber os dados escalonados
previsoresdf = pd.DataFrame(previsores_esc)

In [88]:
previsoresdf

0         1         2         3         4         5         6   \
0     1.019062 -1.019062 -0.330697  0.330697 -0.524435  1.376772 -0.884483   
1    -0.981294  0.981294 -0.330697  0.330697 -0.524435  1.376772 -0.884483   
2    -0.981294  0.981294 -0.330697  0.330697 -0.524435 -0.726337  1.130603   
3    -0.981294  0.981294 -0.330697  0.330697 -0.524435 -0.726337  1.130603   
4     1.019062 -1.019062 -0.330697  0.330697 -0.524435 -0.726337  1.130603   
...        ...       ...       ...       ...       ...       ...       ...   
5980  1.019062 -1.019062 -0.330697  0.330697  1.906814 -0.726337 -0.884483   
5981  1.019062 -1.019062 -0.330697  0.330697 -0.524435  1.376772 -0.884483   
5982 -0.981294  0.981294 -0.330697  0.330697 -0.524435 -0.726337  1.130603   
5983 -0.981294  0.981294 -0.330697  0.330697 -0.524435  1.376772 -0.884483   
5984 -0.981294  0.981294 -0.330697  0.330697 -0.524435  1.376772 -0.884483   

            7         8         9   ...        26        27        28  \
0     1.003515 -0.632973 -0.524435  ... -1.097091 -0.562878 -0.834811   
1     1.003515 -0.632973 -0.524435  ...  0.911502 -0.562878  1.197876   
2     1.003515 -0.632973 -0.524435  ...  0.911502 -0.562878 -0.834811   
3     1.003515 -0.632973 -0.524435  ...  0.911502 -0.562878 -0.834811   
4     1.003515 -0.632973 -0.524435  ...  0.911502 -0.562878 -0.834811   
...        ...       ...       ...  ...       ...       ...       ...   
5980 -0.996497 -0.632973  1.906814  ...  0.911502 -0.562878  1.197876   
5981 -0.996497  1.579845 -0.524435  ... -1.097091 -0.562878  1.197876   
5982  1.003515 -0.632973 -0.524435  ...  0.911502 -0.562878 -0.834811   
5983  1.003515 -0.632973 -0.524435  ...  0.911502 -0.562878 -0.834811   
5984 -0.996497  1.579845 -0.524435  ... -1.097091  1.776584  1.197876   

            29        30        31        32        33        34        35  
0     0.834811  1.837117 -0.710033 -0.527541 -0.528835 -0.957197 -0.393992  
1    -1.197876  1.837117 -0.710033 -0.527541 -0.528835 -0.957197 -0.598453  
2     0.834811 -0.544331  1.408385 -0.527541 -0.528835 -1.161180 -0.495197  
3     0.834811 -0.544331  1.408385 -0.527541 -0.528835 -0.794010 -0.018577  
4     0.834811  1.837117 -0.710033 -0.527541 -0.528835 -1.201976 -0.222354  
...        ...       ...       ...       ...       ...       ...       ...  
5980 -1.197876 -0.544331 -0.710033 -0.527541  1.890949 -1.161180 -1.451855  
5981 -1.197876  1.837117 -0.710033 -0.527541 -0.528835 -0.794010 -0.735216  
5982  0.834811 -0.544331  1.408385 -0.527541 -0.528835 -0.426841 -0.290736  
5983  0.834811  1.837117 -0.710033 -0.527541 -0.528835 -1.242773 -0.735216  
5984 -1.197876  1.837117 -0.710033 -0.527541 -0.528835  1.409006 -0.599137  

[5985 rows x 36 columns]

In [89]:
previsoresdf.describe()

0             1             2             3             4   \
count  5.985000e+03  5.985000e+03  5.985000e+03  5.985000e+03  5.985000e+03   
mean   1.691768e-16  4.630103e-17  5.461147e-17 -5.461147e-17 -9.497647e-18   
std    1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min   -9.812944e-01 -1.019062e+00 -3.306970e-01 -3.023916e+00 -5.244349e-01   
25%   -9.812944e-01 -1.019062e+00 -3.306970e-01  3.306970e-01 -5.244349e-01   
50%   -9.812944e-01  9.812944e-01 -3.306970e-01  3.306970e-01 -5.244349e-01   
75%    1.019062e+00  9.812944e-01 -3.306970e-01  3.306970e-01 -5.244349e-01   
max    1.019062e+00  9.812944e-01  3.023916e+00  3.306970e-01  1.906814e+00   

                 5             6             7             8             9   \
count  5.985000e+03  5.985000e+03  5.985000e+03  5.985000e+03  5.985000e+03   
mean   2.493132e-17  1.780809e-18 -2.374412e-18 -4.036500e-17 -9.497647e-18   
std    1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min   -7.263368e-01 -8.844834e-01 -9.964974e-01 -6.329734e-01 -5.244349e-01   
25%   -7.263368e-01 -8.844834e-01 -9.964974e-01 -6.329734e-01 -5.244349e-01   
50%   -7.263368e-01 -8.844834e-01 -9.964974e-01 -6.329734e-01 -5.244349e-01   
75%    1.376772e+00  1.130603e+00  1.003515e+00  1.579845e+00 -5.244349e-01   
max    1.376772e+00  1.130603e+00  1.003515e+00  1.579845e+00  1.906814e+00   

       ...            26            27            28            29  \
count  ...  5.985000e+03  5.985000e+03  5.985000e+03  5.985000e+03   
mean   ...  4.511382e-17 -2.611853e-17  7.182596e-17 -1.308895e-16   
std    ...  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min    ... -1.097091e+00 -5.628780e-01 -8.348111e-01 -1.197876e+00   
25%    ... -1.097091e+00 -5.628780e-01 -8.348111e-01 -1.197876e+00   
50%    ...  9.115016e-01 -5.628780e-01 -8.348111e-01  8.348111e-01   
75%    ...  9.115016e-01 -5.628780e-01  1.197876e+00  8.348111e-01   
max    ...  9.115016e-01  1.776584e+00  1.197876e+00  8.348111e-01   

                 30            31            32            33            34  \
count  5.985000e+03  5.985000e+03  5.985000e+03  5.985000e+03  5.985000e+03   
mean   7.123235e-18 -5.936030e-18  2.136971e-17  2.018250e-17 -1.400903e-16   
std    1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00  1.000084e+00   
min   -5.443311e-01 -7.100329e-01 -5.275413e-01 -5.288350e-01 -1.324366e+00   
25%   -5.443311e-01 -7.100329e-01 -5.275413e-01 -5.288350e-01 -9.571968e-01   
50%   -5.443311e-01 -7.100329e-01 -5.275413e-01 -5.288350e-01 -1.412646e-01   
75%   -5.443311e-01  1.408385e+00 -5.275413e-01 -5.288350e-01  9.602438e-01   
max    1.837117e+00  1.408385e+00  1.895586e+00  1.890949e+00  1.612989e+00   

                 35  
count  5.985000e+03  
mean   2.475087e-14  
std    1.000084e+00  
min   -1.451855e+00  
25%   -7.338485e-01  
50%   -1.902148e-01  
75%    5.975413e-01  
max    3.023720e+00  

[8 rows x 36 columns]

## Salvando as variáveis
--------------------------------------------------------------------------------


In [90]:
import pickle

In [91]:
# criando arquivo
arq1 = open("classchurn.pk1","wb")  # quando cria "wb", quando lê o arquivo "rb"

In [92]:
# salvando a variável no arquivo
pickle.dump(alvo, arq1)

In [93]:
# fechar arquivo
arq1.close()

In [94]:
# lendo o arquivo
arq1 = open("classchurn.pk1","rb")   

In [95]:
# chamando a variável
alvo = pickle.load(arq1)

In [96]:
alvo

array([0, 0, 1, ..., 1, 0, 0])

# Separando base de treino e base de teste
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [97]:
from sklearn.model_selection import train_test_split

Parâmetros do Train_Test_Split:

arrays : nomes dos atributos previsores e alvo
test_size : tamanho em porcentagem dos dados de teste. Default é none.
train_size : tamanho em porcentagem dos dados de treinamento. Default é none.
randon_state : nomeação de um estado aleatório
shuffle : embaralhamento dos dados aleatórios. Associado com random _state ocorre o mesmo embaralhamento sempre. Default é True.
stratify : possibilidade de dividir os dados de forma estratificada. Default é none. ( Nesse caso é mantida a proporção, isto é, se tem 30% de zeros e 70% de 1 no DataFrame, na separação em treinamento e teste se manterá essa proporção ).

In [302]:
# Separamos 30% dos dados para teste e 70% para treino
x_treino,x_teste,y_treino,y_teste = train_test_split(previsores,alvo,test_size=0.3,random_state=0)

In [212]:
x_treino.shape

(4189, 36)

In [100]:
y_treino.shape

(4189,)

In [101]:
x_teste.shape

(1796, 36)

In [102]:
y_teste.shape

(1796,)

## IDENTIFICANDO OS PREVISORES:

* previsores - dados não tratados
* previsores2 - dados tratados com OneHotEncoder
* previsores_esc - dados tratados com OneHotEncoder e escalonado


# Resultado dos Modelos:
================================================================================

1.  Naive Bayes :
* Acurácia Média: 71.26% / previsores
* Acurácia Média: 68.81% / previsores2
* Acurácia Média: 68.81% / previsores_esc
2.  Máquina de vetores de suporte: 
* A Acurácia Média: 75.89% / previsores
* A Acurácia Média: 75.87% / previsores2
* A Acurácia Média: 79.27% / previsores_esc
3.  Regressão logística:
* A Acurácia Média: 79.38% / previsores
* A Acurácia Média: 79.60% / previsores2
* A Acurácia Média: 79.67% / previsores_esc
4.  KNN: Acurácia Média: 
* A Acurácia Média: 78.20% / previsores
* A Acurácia Média: 77.98% / previsores2
* A Acurácia Média: 77.38% / previsores_esc
5.  Árvore de decisão: Acurácia Média:
* A Acurácia Média: 78.23% / previsores
* A Acurácia Média: 78.28% / previsores2
* A Acurácia Média: 78.28% / previsores_esc
6.  XGBOOST: Acurácia Média: 
* A Acurácia Média: 79.97% / previsores
* A Acurácia Média: 79.74% / previsores2
* A Acurácia Média: 79.45% / previsores_esc
7. CATBOOST: Acurácia Média: 
* A Acurácia Média: 79.73% / previsores
* A Acurácia Média: 79.20% / previsores2
* A Acurácia Média: 79.18% / previsores_esc
* A Acurácia Média: 79.83% / previsores_cat



# Naive Bayes
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------

In [171]:
# Treinamento do algotitmo
from sklearn.naive_bayes import GaussianNB

In [172]:
naive = GaussianNB()

In [173]:
naive.fit(x_treino,y_treino)

GaussianNB()

In [174]:
previsoes_naive = naive.predict(x_teste)
previsoes_naive

array([1, 1, 0, ..., 1, 1, 0])

In [175]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [176]:
accuracy_score(y_teste, previsoes_naive)

0.6737193763919822

In [177]:
confusion_matrix(y_teste,previsoes_naive)

array([[803, 518],
       [ 68, 407]])

In [178]:
print(classification_report(y_teste,previsoes_naive))

              precision    recall  f1-score   support

           0       0.92      0.61      0.73      1321
           1       0.44      0.86      0.58       475

    accuracy                           0.67      1796
   macro avg       0.68      0.73      0.66      1796
weighted avg       0.79      0.67      0.69      1796



## Analise de dados treino

In [179]:
previsoes_treino = naive.predict(x_treino)
previsoes_treino

array([1, 0, 1, ..., 1, 0, 1])

In [180]:
accuracy_score(y_treino,previsoes_treino)

0.6946765337789449

In [181]:
confusion_matrix(y_treino,previsoes_treino)

array([[1966, 1111],
       [ 168,  944]])

## Validação cruzada

In [190]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [191]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [192]:
# Criando o modelo
modelo = GaussianNB()
resultado = cross_val_score(modelo,previsores_esc,alvo,cv=kfold)

In [193]:
resultado

array([0.71      , 0.65      , 0.66      , 0.725     , 0.72      ,
       0.715     , 0.625     , 0.695     , 0.695     , 0.66      ,
       0.725     , 0.73      , 0.7       , 0.7       , 0.615     ,
       0.71859296, 0.73869347, 0.68341709, 0.68341709, 0.71859296,
       0.66331658, 0.68341709, 0.72864322, 0.66834171, 0.63316583,
       0.67336683, 0.69346734, 0.67336683, 0.73366834, 0.62311558])

In [194]:
# Usando a média e desvio padrão
print("Acurácia Média: %.2f%%" %(resultado.mean()*100))

Acurácia Média: 68.81%


# Maquina de vetores de suporte( SVM )
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [230]:
from sklearn.svm import SVC   # Importando a biblioteca SVM especifico para classificação ( SVC )

In [231]:
svm = SVC(kernel='rbf',random_state=1, C=2) # Cria o vetor "svm". A configuração kernel para transformar os dados para aplicação da forma correta
svm.fit(x_treino, y_treino)  # Criação do fit de treinamento

SVC(C=2, random_state=1)

In [232]:
previsoes_svm=svm.predict(x_teste)   # Criação do PREVISOR baseado no svm
previsoes_svm # Visualiza o resultado

array([0, 0, 0, ..., 0, 0, 0])

In [233]:
y_teste # Visualiza a base y de teste

array([1, 0, 0, ..., 0, 0, 1])

In [234]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste, previsoes_svm)*100.0))

Acurácia: 75.61%


In [235]:
confusion_matrix(y_teste, previsoes_svm)

array([[1256,   65],
       [ 373,  102]])

In [236]:
print(classification_report(y_teste, previsoes_svm))

              precision    recall  f1-score   support

           0       0.77      0.95      0.85      1321
           1       0.61      0.21      0.32       475

    accuracy                           0.76      1796
   macro avg       0.69      0.58      0.58      1796
weighted avg       0.73      0.76      0.71      1796



## Analise dados de treino
------------------------------------------------------------------------------

In [237]:
previsoes_treino = svm.predict(x_treino)
previsoes_treino

array([0, 0, 0, ..., 0, 0, 0])

In [238]:
accuracy_score(y_treino, previsoes_treino)

0.7605633802816901

In [239]:
confusion_matrix(y_treino,previsoes_treino)

array([[2942,  135],
       [ 868,  244]])

## Validação Cruzada
-------------------------------------------------------------------------------

In [240]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [241]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [244]:
#Criando o modelo
modelo=SVC(kernel="rbf",random_state=1,C=2.0)
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)

In [245]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 79.27%


# Regressão Logistica
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------
-------------------------------------------------------------------------------


In [247]:
from sklearn.linear_model import LogisticRegression   # Importando biblioteca LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [248]:
logistica = LogisticRegression(random_state=1,max_iter=200, penalty="l2", tol=0.0001,C=1,solver="lbfgs")
logistica.fit(x_treino,y_treino)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning:

lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression



LogisticRegression(C=1, max_iter=200, random_state=1)

In [249]:
logistica.intercept_  # Verifica o resultado do Intercepto

array([-1.2037541])

In [250]:
logistica.coef_  # Verifica o resultado dos coefientes

array([[-4.87571947e-02, -4.57509190e-02, -3.61141942e-01,
         1.18484945e+00, -2.74631136e-01, -6.11265245e-02,
        -2.71247485e-02, -3.89601078e-01,  3.17225704e-01,
         4.13702077e-01, -6.88657314e-02,  4.68156711e-01,
        -6.81670471e-02, -3.55802100e-04]])

In [251]:
previsoes_logistica = logistica.predict(x_teste)
previsoes_logistica

array([0, 0, 0, ..., 0, 0, 0])

In [252]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste,previsoes_logistica)*100))

Acurácia: 79.01%


In [253]:
confusion_matrix(y_teste,previsoes_logistica)

array([[1189,  132],
       [ 245,  230]])

In [254]:
print(classification_report(y_teste,previsoes_logistica))

              precision    recall  f1-score   support

           0       0.83      0.90      0.86      1321
           1       0.64      0.48      0.55       475

    accuracy                           0.79      1796
   macro avg       0.73      0.69      0.71      1796
weighted avg       0.78      0.79      0.78      1796



## Analise dados de treino

In [255]:
previsoes_treino= logistica.predict(x_treino)   # Criando Dataframe para receber dados treino
previsoes_treino

array([0, 0, 0, ..., 0, 0, 0])

In [256]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))   # Verifica a acurácio da base treino

Acurácia: 79.95%


In [257]:
confusion_matrix(y_treino,previsoes_treino)

array([[2792,  285],
       [ 555,  557]])

In [258]:
print(classification_report(y_treino,previsoes_treino))

              precision    recall  f1-score   support

           0       0.83      0.91      0.87      3077
           1       0.66      0.50      0.57      1112

    accuracy                           0.80      4189
   macro avg       0.75      0.70      0.72      4189
weighted avg       0.79      0.80      0.79      4189



## Validação Cruzada

In [259]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [260]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [266]:
#Criando o modelo
modelo=LogisticRegression(random_state=1,max_iter=200, penalty="l2", tol=0.0001,C=1,solver="lbfgs")
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)

In [267]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 79.67%


# K NN - K vizinhos mais proximos
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [284]:
from sklearn.neighbors import KNeighborsClassifier   # Importando a biblioteca

In [285]:
knn = KNeighborsClassifier(n_neighbors=10, metric='minkowski',p=2)  #configurando o KNN
knn.fit(x_treino,y_treino)   # Criando o modelo de treino

KNeighborsClassifier(n_neighbors=10)

In [286]:
previsoes_knn = knn.predict(x_teste)
previsoes_knn

array([0, 0, 0, ..., 0, 0, 0])

In [287]:
print("Acuracia: %.2f%%" % (accuracy_score(y_teste,previsoes_knn)*100))

Acuracia: 77.62%


In [288]:
confusion_matrix(y_teste,previsoes_knn)

array([[1203,  118],
       [ 284,  191]])

In [289]:
print(classification_report(y_teste,previsoes_knn))

              precision    recall  f1-score   support

           0       0.81      0.91      0.86      1321
           1       0.62      0.40      0.49       475

    accuracy                           0.78      1796
   macro avg       0.71      0.66      0.67      1796
weighted avg       0.76      0.78      0.76      1796



## Analise do treino

In [290]:
previsoes_treino= knn.predict(x_treino)   # Criando Dataframe para receber dados treino
previsoes_treino

array([0, 0, 0, ..., 0, 0, 0])

In [291]:
print("Acurácia: %.2f%%" % (accuracy_score(y_treino,previsoes_treino)*100))   # Verifica a acurácio da base treino

Acurácia: 80.69%


In [292]:
confusion_matrix(y_teste,previsoes_knn)

array([[1203,  118],
       [ 284,  191]])

In [293]:
print(classification_report(y_teste,previsoes_knn))

              precision    recall  f1-score   support

           0       0.81      0.91      0.86      1321
           1       0.62      0.40      0.49       475

    accuracy                           0.78      1796
   macro avg       0.71      0.66      0.67      1796
weighted avg       0.76      0.78      0.76      1796



## Validação cruzada

In [294]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [295]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [300]:
#Criando o modelo
modelo=KNeighborsClassifier(n_neighbors=10, metric='minkowski',p=1)
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)

In [301]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 77.38%


# Árvore de decisão
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [303]:
from sklearn.tree import DecisionTreeClassifier

In [304]:
arvore = DecisionTreeClassifier(criterion='entropy', random_state=0,max_depth=3)
arvore.fit(x_treino,y_treino)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [305]:
previsoes_arvore = arvore.predict(x_teste)
previsoes_arvore

array([0, 1, 0, ..., 1, 1, 0])

In [306]:
y_teste

array([1, 0, 0, ..., 0, 0, 1])

In [307]:
print("Acurácia: %.2f%%" % (accuracy_score(y_teste,previsoes_arvore)*100))

Acurácia: 74.83%


In [308]:
confusion_matrix(y_teste,previsoes_arvore)

array([[1049,  272],
       [ 180,  295]])

In [309]:
print(classification_report(y_teste,previsoes_arvore))

              precision    recall  f1-score   support

           0       0.85      0.79      0.82      1321
           1       0.52      0.62      0.57       475

    accuracy                           0.75      1796
   macro avg       0.69      0.71      0.69      1796
weighted avg       0.77      0.75      0.75      1796



## Analise de treino

In [310]:
previsoes_treino=arvore.predict(x_treino)
previsoes_treino

array([0, 0, 0, ..., 0, 0, 0])

In [311]:
accuracy_score(y_treino,previsoes_treino)

0.7648603485318691

In [312]:
confusion_matrix(y_treino,previsoes_treino)

array([[2529,  548],
       [ 437,  675]])

## Validação Cruzada

In [313]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [314]:
# separando os dados em Folds
kfold = KFold(n_splits=30, shuffle=True, random_state=5)

In [319]:
#Criando o modelo
modelo=DecisionTreeClassifier(criterion='entropy',random_state=0,max_depth=3)
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)

In [320]:
# Usando a média e o desvio padrão
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 78.28%


# XGBOOST
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [321]:
from xgboost import XGBClassifier

In [322]:
xg=XGBClassifier(max_depth=2,learning_rate=0.1,n_estimators=150,objective='binary:logistic',random_state=3)
xg.fit(x_treino, y_treino)

XGBClassifier(max_depth=2, n_estimators=150, random_state=3)

In [323]:
previsoes_xg = xg.predict(x_teste)
previsoes_xg 

array([0, 0, 0, ..., 1, 0, 0])

In [324]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_teste,previsoes_xg)*100))

Acurácia: 79.57%


In [325]:
confusion_matrix(y_teste,previsoes_xg)

array([[1179,  142],
       [ 225,  250]])

In [326]:
print(classification_report(y_teste,previsoes_xg))

              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1321
           1       0.64      0.53      0.58       475

    accuracy                           0.80      1796
   macro avg       0.74      0.71      0.72      1796
weighted avg       0.79      0.80      0.79      1796



## Analise de treino

In [327]:
previsoes_treino=xg.predict(x_treino)
previsoes_treino

array([1, 0, 0, ..., 0, 0, 0])

In [328]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_treino,previsoes_treino)*100))

Acurácia: 81.28%


In [329]:
confusion_matrix(y_treino,previsoes_treino)

array([[2793,  284],
       [ 500,  612]])

In [330]:
print(classification_report(y_treino,previsoes_treino))

              precision    recall  f1-score   support

           0       0.85      0.91      0.88      3077
           1       0.68      0.55      0.61      1112

    accuracy                           0.81      4189
   macro avg       0.77      0.73      0.74      4189
weighted avg       0.80      0.81      0.81      4189



## Validação cruzada

In [333]:
from sklearn.model_selection import KFold		
from sklearn.model_selection import cross_val_score		
kfold = KFold(n_splits=30, shuffle=True, random_state=5)		
modelo=XGBClassifier(max_depth=2,learning_rate=0.1,n_estimators=200,objective='binary:logistic',random_state=3)		
resultado=cross_val_score(modelo, previsores_esc,alvo,cv=kfold)		
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))	

 A Acurácia Média: 79.97%


# CATBOOST
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------


In [334]:
# iNSTALAÇÃO
!pip install catboost

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 76.6 MB 106 kB/s 


In [335]:
from catboost import CatBoostClassifier

In [361]:
dados2

Genero  MesesComoCliente  ServicoTelefone  ServicoInternet  \
0          0                 9                1                1   
1          1                 9                1                1   
2          1                 4                1                2   
3          1                13                1                2   
4          0                 3                1                2   
...      ...               ...              ...              ...   
5981       0                 4                1                0   
5982       0                13                1                1   
5983       1                22                1                2   
5984       1                 2                1                1   
5985       1                67                1                1   

      ServicoSegurancaOnline  ServicoBackupOnline  ProtecaoEquipamento  \
0                          0                    1                    0   
1                          0                    0                    0   
2                          0                    0                    1   
3                          0                    1                    1   
4                          0                    0                    0   
...                      ...                  ...                  ...   
5981                       2                    2                    2   
5982                       1                    0                    0   
5983                       0                    0                    0   
5984                       0                    1                    0   
5985                       1                    0                    1   

      ServicoSuporteTecnico  ServicoStreamingTV  ServicoFilmes  TipoContrato  \
0                         1                   1              0             0   
1                         0                   0              1             1   
2                         0                   0              0             1   
3                         0                   1              1             1   
4                         1                   1              0             1   
...                     ...                 ...            ...           ...   
5981                      2                   2              2             1   
5982                      1                   0              0             0   
5983                      0                   0              1             1   
5984                      0                   0              0             1   
5985                      1                   0              1             2   

      FaturaDigital  FormaPagamento  ValorMensal  Churn  
0                 1               0        199.6      0  
1                 0               0        169.7      0  
2                 1               1        184.8      1  
3                 1               1        254.5      1  
4                 1               0        224.7      1  
...             ...             ...          ...    ...  
5981              0               3         44.9      1  
5982              0               0        149.7      0  
5983              1               1        214.7      1  
5984              1               0        149.7      0  
5985              0               0        169.6      0  

[5985 rows x 15 columns]

In [362]:
dados3 = dados2
dados3 ["Churn"].replace({"Nao":0,"Sim":1},inplace=True)

/usr/local/lib/python3.7/dist-packages/pandas/core/generic.py:6619: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy



In [363]:
previsores_cat= dados3.iloc[:,0:14]

In [364]:
alvo_cat= dados3.iloc[:,14]

In [365]:
alvo_cat.head()

0    0
1    0
2    1
3    1
4    1
Name: Churn, dtype: int64

In [366]:
previsores_cat.head()

Genero  MesesComoCliente  ServicoTelefone  ServicoInternet  \
0       0                 9                1                1   
1       1                 9                1                1   
2       1                 4                1                2   
3       1                13                1                2   
4       0                 3                1                2   

   ServicoSegurancaOnline  ServicoBackupOnline  ProtecaoEquipamento  \
0                       0                    1                    0   
1                       0                    0                    0   
2                       0                    0                    1   
3                       0                    1                    1   
4                       0                    0                    0   

   ServicoSuporteTecnico  ServicoStreamingTV  ServicoFilmes  TipoContrato  \
0                      1                   1              0             0   
1                      0                   0              1             1   
2                      0                   0              0             1   
3                      0                   1              1             1   
4                      1                   1              0             1   

   FaturaDigital  FormaPagamento  ValorMensal  
0              1               0        199.6  
1              0               0        169.7  
2              1               1        184.8  
3              1               1        254.5  
4              1               0        224.7

In [367]:
from sklearn.model_selection import train_test_split

In [368]:
x_treino,x_teste,y_treino,y_teste = train_test_split(previsores_cat,alvo_cat,test_size=0.3,random_state=0)

In [369]:
categoricas=["Genero",
             "ServicoTelefone",
             "ServicoInternet",
             "ServicoSegurancaOnline",
             "ServicoBackupOnline",
             "ProtecaoEquipamento",
             "ServicoSuporteTecnico",
             "ServicoStreamingTV",
             "ServicoFilmes",
             "TipoContrato",
             "FaturaDigital",
             "FormaPagamento"
             ]

In [371]:
previsores_cat.dtypes

Genero                      int64
MesesComoCliente            int64
ServicoTelefone             int64
ServicoInternet             int64
ServicoSegurancaOnline      int64
ServicoBackupOnline         int64
ProtecaoEquipamento         int64
ServicoSuporteTecnico       int64
ServicoStreamingTV          int64
ServicoFilmes               int64
TipoContrato                int64
FaturaDigital               int64
FormaPagamento              int64
ValorMensal               float64
dtype: object

In [372]:
previsores_cat

Genero  MesesComoCliente  ServicoTelefone  ServicoInternet  \
0          0                 9                1                1   
1          1                 9                1                1   
2          1                 4                1                2   
3          1                13                1                2   
4          0                 3                1                2   
...      ...               ...              ...              ...   
5981       0                 4                1                0   
5982       0                13                1                1   
5983       1                22                1                2   
5984       1                 2                1                1   
5985       1                67                1                1   

      ServicoSegurancaOnline  ServicoBackupOnline  ProtecaoEquipamento  \
0                          0                    1                    0   
1                          0                    0                    0   
2                          0                    0                    1   
3                          0                    1                    1   
4                          0                    0                    0   
...                      ...                  ...                  ...   
5981                       2                    2                    2   
5982                       1                    0                    0   
5983                       0                    0                    0   
5984                       0                    1                    0   
5985                       1                    0                    1   

      ServicoSuporteTecnico  ServicoStreamingTV  ServicoFilmes  TipoContrato  \
0                         1                   1              0             0   
1                         0                   0              1             1   
2                         0                   0              0             1   
3                         0                   1              1             1   
4                         1                   1              0             1   
...                     ...                 ...            ...           ...   
5981                      2                   2              2             1   
5982                      1                   0              0             0   
5983                      0                   0              1             1   
5984                      0                   0              0             1   
5985                      1                   0              1             2   

      FaturaDigital  FormaPagamento  ValorMensal  
0                 1               0        199.6  
1                 0               0        169.7  
2                 1               1        184.8  
3                 1               1        254.5  
4                 1               0        224.7  
...             ...             ...          ...  
5981              0               3         44.9  
5982              0               0        149.7  
5983              1               1        214.7  
5984              1               0        149.7  
5985              0               0        169.6  

[5985 rows x 14 columns]

In [373]:
catboost= CatBoostClassifier(task_type='CPU',iterations=300, learning_rate=0.05,depth=5,random_state=5,eval_metric='Accuracy')

In [374]:
catboost.fit(x_treino,y_treino,cat_features=categoricas,plot=True,eval_set=(x_teste,y_teste))

MetricVisualizer(layout=Layout(align_self='stretch', height='500px'))

0:	learn: 0.7724994	test: 0.7689310	best: 0.7689310 (0)	total: 70.2ms	remaining: 21s
1:	learn: 0.7617570	test: 0.7628062	best: 0.7689310 (0)	total: 77.2ms	remaining: 11.5s
2:	learn: 0.7818095	test: 0.7828508	best: 0.7828508 (2)	total: 90.8ms	remaining: 8.99s
3:	learn: 0.7877775	test: 0.7828508	best: 0.7828508 (2)	total: 103ms	remaining: 7.58s
4:	learn: 0.7901647	test: 0.7878619	best: 0.7878619 (4)	total: 115ms	remaining: 6.8s
5:	learn: 0.7913583	test: 0.7878619	best: 0.7878619 (4)	total: 125ms	remaining: 6.14s
6:	learn: 0.7904034	test: 0.7873051	best: 0.7878619 (4)	total: 135ms	remaining: 5.66s
7:	learn: 0.7927906	test: 0.7861915	best: 0.7878619 (4)	total: 145ms	remaining: 5.3s
8:	learn: 0.7908809	test: 0.7873051	best: 0.7878619 (4)	total: 164ms	remaining: 5.29s
9:	learn: 0.7908809	test: 0.7873051	best: 0.7878619 (4)	total: 173ms	remaining: 5.03s
10:	learn: 0.7920745	test: 0.7856347	best: 0.7878619 (4)	total: 184ms	remaining: 4.84s
11:	learn: 0.7932681	test: 0.7861915	best: 0.7878619 (

In [375]:
previsoes_cat = catboost.predict(x_teste)
previsoes_cat

array([0, 0, 0, ..., 0, 0, 0])

In [376]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_teste,previsoes_cat)*100))

Acurácia: 79.84%


In [377]:
confusion_matrix(y_teste,previsoes_cat)

array([[1211,  110],
       [ 252,  223]])

## Analise dados Treino

In [378]:
previsoes_treino = catboost.predict(x_treino)
previsoes_treino

array([1, 0, 0, ..., 0, 0, 0])

In [379]:
print ('Acurácia: %.2f%%' % (accuracy_score(y_treino,previsoes_treino)*100))

Acurácia: 80.83%


In [380]:
confusion_matrix(y_treino,previsoes_treino)

array([[2846,  231],
       [ 572,  540]])

## VALIDAÇÃO CRUZADA

In [387]:
from sklearn.model_selection import KFold		
from sklearn.model_selection import cross_val_score		
kfold = KFold(n_splits=30, shuffle=True, random_state=5)		
modelo=CatBoostClassifier(task_type='CPU',iterations=100, learning_rate=0.1,depth=8,random_state=8,eval_metric='Accuracy')		
resultado=cross_val_score(modelo, previsores_cat,alvo,cv=kfold)		
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

0:	learn: 0.7875540	total: 3.52ms	remaining: 349ms
1:	learn: 0.7987900	total: 7.36ms	remaining: 360ms
2:	learn: 0.7960242	total: 11.8ms	remaining: 381ms
3:	learn: 0.7961971	total: 14.9ms	remaining: 357ms
4:	learn: 0.7982714	total: 18.6ms	remaining: 353ms
5:	learn: 0.7994814	total: 22.4ms	remaining: 351ms
6:	learn: 0.7984443	total: 24.8ms	remaining: 329ms
7:	learn: 0.7967156	total: 26.9ms	remaining: 310ms
8:	learn: 0.7977528	total: 29.3ms	remaining: 296ms
9:	learn: 0.8005186	total: 33.9ms	remaining: 305ms
10:	learn: 0.8008643	total: 37.7ms	remaining: 305ms
11:	learn: 0.8000000	total: 42ms	remaining: 308ms
12:	learn: 0.7994814	total: 51.9ms	remaining: 347ms
13:	learn: 0.7984443	total: 54.1ms	remaining: 332ms
14:	learn: 0.7994814	total: 56.4ms	remaining: 319ms
15:	learn: 0.7987900	total: 58.1ms	remaining: 305ms
16:	learn: 0.7982714	total: 60.3ms	remaining: 295ms
17:	learn: 0.7994814	total: 64.1ms	remaining: 292ms
18:	learn: 0.8003457	total: 73.1ms	remaining: 312ms
19:	learn: 0.8027658	tot

In [388]:
print(" A Acurácia Média: %.2f%%" % (resultado.mean()*100))

 A Acurácia Média: 79.73%
